#!/usr/bin/env bash
#
# Refresh the list of Cloudflare IP ranges for nginx.
#
# Cloudflare adds ranges from time to time. Left stale, traffic arriving from
# a new range stops getting real_ip, and the app sees the Cloudflare edge
# address instead of the visitor's — which is what breaks the rate limiter.
#
# Run by hand:
#   sudo bash /opt/ethiclens/deploy/update-cloudflare-ips.sh
#
# Run monthly from cron:
#   sudo crontab -e
#   17 4 1 * * bash /opt/ethiclens/deploy/update-cloudflare-ips.sh >> /var/log/cf-ips.log 2>&1

set -euo pipefail

OUT=/etc/nginx/cloudflare-realip.conf
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "[cf] fetching ranges from Cloudflare..."

V4="$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4)"
V6="$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6)"

# If the response is empty or nonsense, leave the existing file alone.
# Writing an empty file disables real_ip entirely.
if [ -z "$V4" ] || [ -z "$V6" ]; then
  echo "[cf] error: empty response. The current file is unchanged." >&2
  exit 1
fi

{
  echo "# Do not edit this file - it is generated by deploy/update-cloudflare-ips.sh."
  echo "# Generated: $(date -Is)"
  echo
  echo "# ---- IPv4 ----"
  echo "$V4" | while read -r cidr; do
    [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
  done
  echo
  echo "# ---- IPv6 ----"
  echo "$V6" | while read -r cidr; do
    [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
  done
  echo
  echo "real_ip_header    CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$TMP"

COUNT="$(grep -c set_real_ip_from "$TMP")"
if [ "$COUNT" -lt 10 ]; then
  echo "[cf] error: only $COUNT ranges found - fewer than expected. Aborted." >&2
  exit 1
fi

install -m 0644 "$TMP" "$OUT"
echo "[cf] wrote $COUNT ranges to $OUT."

# Test before reloading: a broken file would take nginx down.
if nginx -t; then
  systemctl reload nginx
  echo "[cf] nginx reloaded."
else
  echo "[cf] the nginx configuration is invalid - not reloaded." >&2
  exit 1
fi
